name: jose_jwt
version: 0.0.1
author: Jonas Kello <jonas.kello@gmail.com>
description: Port of Nimbus-JOSE-JWT for Dart.
homepage: https://github.com/jonaskello/jose_jwt
environment:
  sdk: '>=1.3.0 <2.0.0'
dependencies:
  cipher: '>=0.7.1 <0.8.0'
  crypto: '>=0.9.0 <0.10.0'
#  logging: '>=0.9.1+1 <0.10.0'
#  option: '>=0.3.3 <0.4.0'
  collection: ">=1.1.0 <2.0.0"
  bignum: ">=0.0.6 <0.1.0"
dev_dependencies:
#  asn1lib: '>=0.4.1 <0.5.0'
  unittest: '>=0.10.0 <0.11.0'
  uuid: ">=0.5.0 <0.6.0"
